server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

oauth2-login-example:
  allowed-origins: https://127.0.0.1:4200
